### ISSUE TITLE
Snippets Could Be Standardized

### ISSUE THREAD

**Issue by james0r** [frontity/step-by-step-tutorial#20]
The snippets in this tutorial seem a bit inconsistent and confusing. I guess i'm just putting this up to see if it's just my style, or if others are a bit confused by the snippets.

Sometimes the imports in their entirety are shown, sometimes not.

Sometimes ellipses are used, sometimes not.

I dunno, anyone else little bit thrown off?

**Comment by mburridge** [comment]
Hi @james0r 

Thanks for your comments. Generally our approach in the tutorial is just to show what's changed in the code snippets, but with enough surrounding context for learners to know where to put the new/amended code.

Where the contents of the whole file is displayed we indicate that it is the case by saying somthing like "...our index.js file can now look like this:" as, for example, on [this page](https://tutorial.frontity.org/part2-adding-a-menu/use-the-link-component).

We feel it is important for people learning Frontity to fully understand the code that they're writing and that it's helpful to give them the context of the code so that they have to do some thinking about the code they're editing, rather than giving them the full file that they can just copy and paste.

In addition, with some of the longer files if the full code was presented in each example it might be harder to determine where the changes are.

Remember that if you do want to see the full code for a file that you can download the project up to each stage, using the instructions that can be found on the ["Checking your progress" page](https://tutorial.frontity.org/checking-your-progress).

It will be interesting to hear your thoughts in the light of the above comments, and it would be interesting to see what opinions other members of the community have on this.

Thanks again for your comments, and we hope that your learning experience wasn't too impeded by this.

**Comment by james0r** [comment]
Thanks so much for your response.

Yes at some points I realize I was rushing and skipping certain critical sections. For example, I skipped styled components because I was familiar with them already then realized the build would fail because I hadn't declared at Header styled component that is used in a later section.

At any rate, I'm enjoying the tutorial and appreciate your response.
